# Default values for go-k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
restartPolicy: Never
# Evaluated by the post-install hook

image:
  repository:  alokhom/go-k8s
  tag: 0.1.1
  pullPolicy: IfNotPresent
service:
  name: go-app
  type: ClusterIp
  externalPort: 3000
  internalPort: 3000

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi


